"""empty message

Revision ID: 108ca57e60b1
Revises: 8d58a8881afc
Create Date: 2025-07-22 02:54:54.778495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '108ca57e60b1'
down_revision: Union[str, None] = '8d58a8881afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS user_memories CASCADE')
    op.execute('DROP TABLE IF EXISTS menu_images CASCADE')
    op.add_column('tenants', sa.Column('menu_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'menu_image_url')
    op.create_table('menu_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name='fk_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='menu_images_pkey')
    )
    op.create_table('user_memories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_memories_pkey')
    )
    op.create_index('idx_user_memories_session_id', 'user_memories', ['session_id'], unique=False)
    # ### end Alembic commands ###
