""""migration"

Revision ID: 1119103439c7
Revises: f66578f570ad
Create Date: 2025-07-26 13:25:34.606224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1119103439c7'
down_revision: Union[str, None] = 'f66578f570ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocoes', sa.Column('descricao_para_ia', sa.Text(), nullable=True))
    op.add_column('promocoes', sa.Column('condicao_json', sa.JSON(), nullable=True))
    op.add_column('promocoes', sa.Column('acao_json', sa.JSON(), nullable=True))
    op.add_column('promocoes', sa.Column('is_ativa', sa.Boolean(), nullable=True))
    op.drop_column('promocoes', 'tipo_desconto')
    op.drop_column('promocoes', 'condicao_ativacao')
    op.drop_column('promocoes', 'dia_semana_ativo')
    op.drop_column('promocoes', 'tipo_promocao')
    op.drop_column('promocoes', 'valor_desconto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocoes', sa.Column('valor_desconto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('promocoes', sa.Column('tipo_promocao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('promocoes', sa.Column('dia_semana_ativo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('promocoes', sa.Column('condicao_ativacao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('promocoes', sa.Column('tipo_desconto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('promocoes', 'is_ativa')
    op.drop_column('promocoes', 'acao_json')
    op.drop_column('promocoes', 'condicao_json')
    op.drop_column('promocoes', 'descricao_para_ia')
    # ### end Alembic commands ###
