""""Estrutura_relacional_de_produtos"

Revision ID: 615e5c534025
Revises: a61e453a55c6
Create Date: 2025-07-24 15:57:27.032345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615e5c534025'
down_revision: Union[str, None] = 'a61e453a55c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcionais',
    sa.Column('id_opcional', sa.Integer(), nullable=False),
    sa.Column('nome_opcional', sa.String(), nullable=False),
    sa.Column('tipo_opcional', sa.String(), nullable=False),
    sa.Column('preco_adicional', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_opcional')
    )
    op.create_index(op.f('ix_opcionais_id_opcional'), 'opcionais', ['id_opcional'], unique=False)
    op.create_table('promocoes',
    sa.Column('id_promocao', sa.Integer(), nullable=False),
    sa.Column('nome_promocao', sa.String(), nullable=False),
    sa.Column('tipo_promocao', sa.String(), nullable=True),
    sa.Column('condicao_ativacao', sa.String(), nullable=True),
    sa.Column('tipo_desconto', sa.String(), nullable=True),
    sa.Column('valor_desconto', sa.String(), nullable=True),
    sa.Column('dia_semana_ativo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_promocao')
    )
    op.create_index(op.f('ix_promocoes_id_promocao'), 'promocoes', ['id_promocao'], unique=False)
    op.create_table('menu_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_images_id'), 'menu_images', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=False),
    sa.Column('descricao_produto', sa.Text(), nullable=True),
    sa.Column('categoria_produto', sa.String(), nullable=True),
    sa.Column('preco_base', sa.Float(), nullable=False),
    sa.Column('tempo_preparo_min', sa.Integer(), nullable=True),
    sa.Column('disponivel_hoje', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_index(op.f('ix_produtos_categoria_produto'), 'produtos', ['categoria_produto'], unique=False)
    op.create_index(op.f('ix_produtos_id_produto'), 'produtos', ['id_produto'], unique=False)
    op.create_index(op.f('ix_produtos_nome_produto'), 'produtos', ['nome_produto'], unique=False)
    op.create_table('produto_opcional',
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('opcional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcional_id'], ['opcionais.id_opcional'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id_produto'], )
    )
    op.create_table('produto_promocao',
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('promocao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id_produto'], ),
    sa.ForeignKeyConstraint(['promocao_id'], ['promocoes.id_promocao'], )
    )
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_retrieval_key'), table_name='products')
    op.drop_table('products')
    op.drop_column('tenants', 'menu_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('menu_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('retrieval_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publico_alvo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('principais_funcionalidades', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('limitacoes_observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('produto_promocao', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preco_promotions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('combo_product', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tempo_preparo_minutos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('products_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_retrieval_key'), 'products', ['retrieval_key'], unique=True)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_table('produto_promocao')
    op.drop_table('produto_opcional')
    op.drop_index(op.f('ix_produtos_nome_produto'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id_produto'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria_produto'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_menu_images_id'), table_name='menu_images')
    op.drop_table('menu_images')
    op.drop_index(op.f('ix_promocoes_id_promocao'), table_name='promocoes')
    op.drop_table('promocoes')
    op.drop_index(op.f('ix_opcionais_id_opcional'), table_name='opcionais')
    op.drop_table('opcionais')
    # ### end Alembic commands ###
