"""Adiciona a coluna personality_id na tabela tenants

Revision ID: 682014ff2072
Revises: 1119103439c7
Create Date: 2025-07-27 13:13:13.980251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682014ff2072'
down_revision: Union[str, None] = '1119103439c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE tenants SET id_pronpt = NULL WHERE id_pronpt ~ '[^0-9]'")
    op.drop_constraint(op.f('personalities_tenant_id_fkey'), 'personalities', type_='foreignkey')
    op.drop_column('personalities', 'tenant_id')
    op.add_column('tenants', sa.Column('personality_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tenants_id_pronpt_fkey'), 'tenants', type_='foreignkey')
    op.alter_column('tenants', 'id_pronpt',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='id_pronpt::integer')
    
    op.create_foreign_key(op.f('fk_tenants_personality_id'), 'tenants', 'personalities', ['personality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(op.f('fk_tenants_personality_id'), 'tenants', type_='foreignkey')
    except Exception as e:
        print(f"Could not drop constraint, probably because it does not exist: {e}")
    
    op.drop_column('tenants', 'personality_id')
    op.alter_column('tenants', 'id_pronpt',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_foreign_key(op.f('tenants_id_pronpt_fkey'), 'tenants', 'personalities', ['id_pronpt'], ['name'])
    op.add_column('personalities', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('personalities_tenant_id_fkey'), 'personalities', 'tenants', ['tenant_id'], ['tenant_id'])
    # ### end Alembic commands ###
