"""empty message

Revision ID: 6e816ca92446
Revises: 108ca57e60b1
Create Date: 2025-07-22 03:02:01.939652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e816ca92446'
down_revision: Union[str, None] = '108ca57e60b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tenants ADD COLUMN IF NOT EXISTS freight_config TEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'freight_config')
    # ### end Alembic commands ###
