"""'Add_tenant_isolation_and_order_features'

Revision ID: a61e453a55c6
Revises: 2d7488faf817
Create Date: 2025-07-23 10:15:46.176268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61e453a55c6'
down_revision: Union[str, None] = '2d7488faf817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.String(), nullable=False),
    sa.Column('delivery_method', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('freight_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_user_phone'), 'orders', ['user_phone'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_phone'), 'user_addresses', ['user_phone'], unique=False)
    # 1. Adiciona a coluna permitindo nulos temporariamente
    op.add_column('interactions', sa.Column('tenant_id', sa.String(), nullable=True))

    # 2. Atualiza as linhas existentes com um valor padrão
    # Use um tenant_id que exista no seu banco de dados. Se não tiver certeza, verifique.
    op.execute("UPDATE interactions SET tenant_id = 'ideallys_teste' WHERE tenant_id IS NULL")

    # 3. Altera a coluna para não permitir mais nulos
    op.alter_column('interactions', 'tenant_id', nullable=False)

    op.create_foreign_key('fk_interactions_tenant_id', 'interactions', 'tenants', ['tenant_id'], ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'tenant_id')
    op.drop_index(op.f('ix_user_addresses_user_phone'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_orders_user_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
