"""'add_tenant_id_to_opcionais_and_promocoes'

Revision ID: f66578f570ad
Revises: 615e5c534025
Create Date: 2025-07-24 22:59:42.846695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66578f570ad'
down_revision: Union[str, None] = '615e5c534025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opcionais', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'opcionais', 'tenants', ['tenant_id'], ['tenant_id'])
    op.add_column('promocoes', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'promocoes', 'tenants', ['tenant_id'], ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocoes', type_='foreignkey')
    op.drop_column('promocoes', 'tenant_id')
    op.drop_constraint(None, 'opcionais', type_='foreignkey')
    op.drop_column('opcionais', 'tenant_id')
    # ### end Alembic commands ###
